# Generated by Django 2.1.3 on 2018-12-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorinfo',
            name='time',
            field=models.CharField(max_length=20, verbose_name='日期'),
        ),
    ]
